name: Capture Cotes

on:
  schedule:
    - cron: '0 * * * *'  # Exécute toutes les heures
  workflow_dispatch:     # Permet de lancer manuellement

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pandas beautifulsoup4 pytz

      - name: Run script
        run: python capter_cotes_auto.py